### ISSUE TITLE
Please focus on the requirements, you still have the email requirements missing

### ISSUE THREAD

**Issue by giselacostamindera** [MeFay/RestAPI#13]
Test that we must do:
If userId does not match user.getUserId-> HttpStatus.BAD_REQUEST -> "UserId and request body id do not match"
If id, name or email null or empty -> HttpStatus.BAD_REQUEST -> "User Id user name and user email cannot be null or empty"
If user does not exist -> HttpStatus.NOT_FOUND -> "UserId does not exist"
**If user already exists with different email (cannot change email) -> HttpStatus.CONFLICT "User email cannot be updated"**
If user updates successfully -> HttpStatus.OK

**Comment by MeFay** [comment]
I think I did all
